In [1]:
from sklearn.datasets import load_digits

In [2]:
from sklearn.svm import SVC

In [3]:
import pandas as pd

In [4]:
digits=load_digits()

In [6]:
df=pd.DataFrame(digits.data,columns=digits.feature_names)

In [8]:
df['numbers']=digits.target

In [9]:
df['numbers']=df['numbers'].apply(lambda x:digits.target_names[x])

In [12]:
from sklearn.model_selection import cross_val_score

In [14]:
cross_val_score(SVC(kernel='rbf',C=10,gamma='auto'),digits.data,digits.target,cv=5)

array([0.45277778, 0.46944444, 0.47910864, 0.47910864, 0.50139276])

In [15]:
cross_val_score(SVC(kernel='linear',C=10,gamma='auto'),digits.data,digits.target,cv=5)

array([0.96388889, 0.91944444, 0.96657382, 0.9637883 , 0.92479109])

In [16]:
cross_val_score(SVC(kernel='linear',C=20,gamma='auto'),digits.data,digits.target,cv=5)

array([0.96388889, 0.91944444, 0.96657382, 0.9637883 , 0.92479109])

In [17]:
import numpy as np

In [19]:
kernels=['linear', 'rbf']
C=[1,10,20]
avg_score={}
for kval in kernels:
    for cval in C:
        cv_score=cross_val_score(SVC(kernel=kval,C=cval,gamma='auto'),digits.data,digits.target,cv=5)
        avg_score[kval +'_'+ str(cval)] = np.average(cv_score)
avg_score

{'linear_1': 0.9476973073351903,
 'linear_10': 0.9476973073351903,
 'linear_20': 0.9476973073351903,
 'rbf_1': 0.448545341999381,
 'rbf_10': 0.47636645001547506,
 'rbf_20': 0.47636645001547506}

In [20]:
from sklearn.model_selection import GridSearchCV

In [23]:
clf= GridSearchCV(SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['linear', 'poly', 'rbf', 'sigmoid']
},cv=5,return_train_score=False)
clf.fit(digits.data,digits.target)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [25]:
clf.cv_results_

{'mean_fit_time': array([0.06436052, 0.07315378, 0.7273509 , 0.50748668, 0.06355977,
        0.0723547 , 0.69577003, 0.43912826, 0.06615977, 0.07255416,
        0.72315354, 0.43473053]),
 'std_fit_time': array([0.00483919, 0.00342683, 0.01741694, 0.03359128, 0.00319818,
        0.00279898, 0.00318453, 0.00908568, 0.00461929, 0.00241552,
        0.04331917, 0.00622426]),
 'mean_score_time': array([0.01499071, 0.01838889, 0.08394799, 0.06356053, 0.01479125,
        0.01938858, 0.08254805, 0.0579649 , 0.01499047, 0.01838894,
        0.08274908, 0.06056223]),
 'std_score_time': array([0.00089394, 0.00080054, 0.00252896, 0.00682491, 0.00040007,
        0.00185372, 0.00272592, 0.00089474, 0.00063264, 0.00048953,
        0.00171881, 0.00162413]),
 'param_C': masked_array(data=[1, 1, 1, 1, 10, 10, 10, 10, 20, 20, 20, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value='?',
             dtype=object

In [27]:
df=pd.DataFrame(clf.cv_results_)

In [28]:
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0        0.064361      0.004839         0.014991        0.000894       1   
1        0.073154      0.003427         0.018389        0.000801       1   
2        0.727351      0.017417         0.083948        0.002529       1   
3        0.507487      0.033591         0.063561        0.006825       1   
4        0.063560      0.003198         0.014791        0.000400      10   
5        0.072355      0.002799         0.019389        0.001854      10   
6        0.695770      0.003185         0.082548        0.002726      10   
7        0.439128      0.009086         0.057965        0.000895      10   
8        0.066160      0.004619         0.014990        0.000633      20   
9        0.072554      0.002416         0.018389        0.000490      20   
10       0.723154      0.043319         0.082749        0.001719      20   
11       0.434731      0.006224         0.060562        0.001624      20   

   param_kernel                          params  split0_test_score  \
0        linear    {'C': 1, 'kernel': 'linear'}           0.963889   
1          poly      {'C': 1, 'kernel': 'poly'}           0.983333   
2           rbf       {'C': 1, 'kernel': 'rbf'}           0.411111   
3       sigmoid   {'C': 1, 'kernel': 'sigmoid'}           0.100000   
4        linear   {'C': 10, 'kernel': 'linear'}           0.963889   
5          poly     {'C': 10, 'kernel': 'poly'}           0.983333   
6           rbf      {'C': 10, 'kernel': 'rbf'}           0.452778   
7       sigmoid  {'C': 10, 'kernel': 'sigmoid'}           0.100000   
8        linear   {'C': 20, 'kernel': 'linear'}           0.963889   
9          poly     {'C': 20, 'kernel': 'poly'}           0.983333   
10          rbf      {'C': 20, 'kernel': 'rbf'}           0.452778   
11      sigmoid  {'C': 20, 'kernel': 'sigmoid'}           0.100000   

    split1_test_score  split2_test_score  split3_test_score  \
0            0.919444           0.966574           0.963788   
1            0.944444           0.980501           0.988858   
2            0.450000           0.454039           0.448468   
3            0.100000           0.103064           0.100279   
4            0.919444           0.966574           0.963788   
5            0.944444           0.980501           0.988858   
6            0.469444           0.479109           0.479109   
7            0.100000           0.103064           0.100279   
8            0.919444           0.966574           0.963788   
9            0.944444           0.980501           0.988858   
10           0.469444           0.479109           0.479109   
11           0.100000           0.103064           0.100279   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
0            0.924791         0.947697        0.020978                4  
1            0.947075         0.968842        0.019056                1  
2            0.479109         0.448545        0.021761                9  
3            0.100279         0.100724        0.001177               10  
4            0.924791         0.947697        0.020978                4  
5            0.947075         0.968842        0.019056                1  
6            0.501393         0.476366        0.015784                7  
7            0.100279         0.100724        0.001177               10  
8            0.924791         0.947697        0.020978                4  
9            0.947075         0.968842        0.019056                1  
10           0.501393         0.476366        0.015784                7  
11           0.100279         0.100724        0.001177               10

In [29]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0        1       linear         0.947697
1        1         poly         0.968842
2        1          rbf         0.448545
3        1      sigmoid         0.100724
4       10       linear         0.947697
5       10         poly         0.968842
6       10          rbf         0.476366
7       10      sigmoid         0.100724
8       20       linear         0.947697
9       20         poly         0.968842
10      20          rbf         0.476366
11      20      sigmoid         0.100724

In [30]:
clf.best_score_

0.96884246363355

In [31]:
clf.best_params_

{'C': 1, 'kernel': 'poly'}

In [32]:
from sklearn.model_selection import RandomizedSearchCV
rs=RandomizedSearchCV(SVC(gamma='auto'),{
    'C':[1,10,200],
    'kernel':['rbf','linear','poly','sigmoid']
},cv=5,return_train_score=False,n_iter=4)

In [36]:
rs.fit(digits.data,digits.target)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 200],
                                        'kernel': ['rbf', 'linear', 'poly',
                                                   'sigmoid']})

In [37]:
pd.DataFrame(rs.cv_results_)[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0     200          rbf         0.476366
1     200         poly         0.968842
2     200       linear         0.947697
3       1       linear         0.947697

In [41]:
rs.best_score_

0.96884246363355

In [42]:
rs.best_params_

{'kernel': 'poly', 'C': 200}

In [43]:
dir(rs)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_is_fitted',
 '_check_n_features',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_validate_data',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'iid',
 'inverse_transform',
 'multimetric_',
 'n_features_in_',
 'n_iter',
 'n_jobs',
 'n_splits_',
 'param_di