In [1]:
import numpy as np

In [2]:
x=np.array([1,2,3,4,5])

In [3]:
type(x)

numpy.ndarray

In [4]:
print(x[0])
print(x[1])
print(x[2])
print(x[3])
print(x[4])


1
2
3
4
5


In [5]:
x[4]=45

In [6]:
x

array([ 1,  2,  3,  4, 45])

In [10]:
x=np.arange(1,10).reshape(3,3)

In [11]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
print(x[2,2])

9


In [15]:
x=np.arange(5)

In [16]:
x

array([0, 1, 2, 3, 4])

In [17]:
x=np.append(x,[5,6,7])

In [18]:
x

array([0, 1, 2, 3, 4, 5, 6, 7])

In [25]:
x=np.arange(1,10).reshape(3,3)

In [27]:
y=np.append(x,[[3,5,7]],axis=0)

In [24]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [3, 5, 7]])

In [29]:
x=np.arange(1,10).reshape(3,3)

In [30]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
y=np.insert(x,1,[[6,7,8]], axis=0)

In [32]:
y

array([[1, 2, 3],
       [6, 7, 8],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
z=np.insert(y,1,[[2],[9],[4],[3]],axis =1)

In [34]:
z

array([[1, 2, 9, 4, 3, 2, 3],
       [6, 2, 9, 4, 3, 7, 8],
       [4, 2, 9, 4, 3, 5, 6],
       [7, 2, 9, 4, 3, 8, 9]])