In [3]:
import numpy as np

In [4]:
a= np.random.random(1000)

In [5]:
a

array([5.25280070e-01, 1.16614831e-01, 5.80660021e-01, 5.76990789e-01,
       3.56533892e-01, 2.00726899e-01, 7.88677673e-01, 7.83898341e-01,
       7.40688277e-01, 1.25136475e-01, 5.08812459e-01, 4.57919624e-01,
       3.28513222e-01, 1.19647833e-02, 2.87281282e-01, 2.05975532e-03,
       8.34709433e-01, 5.62695171e-01, 9.48439662e-01, 6.61446572e-01,
       4.14130775e-01, 4.28376778e-01, 5.22836258e-01, 2.65629525e-01,
       2.46899225e-01, 6.59349071e-01, 2.38449552e-01, 9.25199613e-01,
       3.54429623e-01, 7.72448332e-01, 3.50629114e-01, 5.55848727e-01,
       5.81571666e-01, 1.50157489e-01, 4.06039703e-02, 3.11879041e-02,
       1.63713826e-01, 4.18713392e-01, 5.93672308e-01, 6.25155785e-01,
       9.32832325e-01, 5.73461041e-01, 5.79932608e-01, 4.02394407e-01,
       3.45878246e-01, 8.76425504e-01, 1.36079114e-01, 1.90733409e-01,
       1.56872141e-01, 9.15449090e-01, 6.32205240e-01, 2.08333051e-01,
       7.47837870e-01, 1.54048925e-01, 1.77280741e-01, 4.82910784e-01,
      

In [6]:
import time

In [8]:
start=time.time()
mean1=sum(a)/len(a)
print(time.time()-start)

0.0010004043579101562


In [10]:
start=time.time()
np.mean(a)
print(time.time()-start)

0.0009989738464355469


In [11]:
a= np.array([1,2,3,4,5])

In [12]:
a

array([1, 2, 3, 4, 5])

In [13]:
typr(a)

NameError: name 'typr' is not defined

In [14]:
type(a)

numpy.ndarray

In [15]:
a.shape

(5,)

In [16]:
a=np.array([[1,2,3],[4,5,6]])

In [17]:
a.shape

(2, 3)

In [18]:
a

array([[1, 2, 3],
       [4, 5, 6]])